name: ACM Official Website
on:
    pull_request:
        branches: [main, dev]
    workflow_dispatch:

jobs:
    format:
        name: formatting
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: acm-ucr/formatting@v2
    lint:
        name: linting
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: acm-ucr/linting@v2
    build:
        name: build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: acm-ucr/build@v2
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Run Cypress
              uses: cypress-io/github-action@v3
              with:
                  project: ./
                  browser: chrome
                  build: npm run build
                  start: npm run start
                  wait-on: "http://localhost:3000"
